### ISSUE TITLE
[Documentation Issue 📚]: Broken link to FTP Ltd

### ISSUE THREAD

**Issue by drmuelr** [zer0Kerbal/FuelTanksPlus#158]
### Which document/file?

readme.md and all similar content

### Brief description of your issue

The link to FTP Limited is broken everywhere in the documentation I've seen, including on the KSP forums. This is problematic since it's a dependency. Had to search the forums to find it: https://forum.kerbalspaceprogram.com/index.php?/topic/209628-1125-ftp-ltd-ftpl-v09991-prerelease-edition-16-jan-2023/

**Comment by zer0Kerbal** [comment]
release @drmuelr incoming.
