### ISSUE TITLE
Localization - Italian (Italiano) <it-it.cfg> 

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/FuelTanksPlus#19]
From Localization created by [zer0Kerbal](https://github.com/zer0Kerbal): zer0Kerbal/Localization#8  

Localization - [Italian (Italiano)][IT] <it-it.cfg> 

### GameData

- [ ] add it-it.cfg  

### Translation

- [ ] [![Italiano][IT]][IT] [Italian (Italiano)][IT] <it-it.cfg>  

[IT]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Italian-flag-sm.png "Italiano" 

### Update Documentation

- [x]  mod Readme 🔢 
- [x]  releaseNotes.md 🧾 

### GitHub Issues

- [x] assign to zer0Kerbal
- [x] assign projects (user and repo)
- [x] assign label: Localization
- [x] assign label: help-wanted
- [x] assign milestone: Localization - Italian (Italiano) <it-it.cfg>

### Update Social Media

- [x] CurseForge
- [x] CKAN
- [x] Forum
- [x] GitHub
- [x] Patreon
- [x] Reddit
- [x] SpaceDock

### Wiki

- [x] update localization list 
  

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization" 
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

**Comment by MattNot** [comment]
Hi man! Can I do this for hacktoberfest? :P

**Comment by zer0Kerbal** [comment]
> Hi man! Can I do this for hacktoberfest? :P

yes please.

All should be ready for you.

**Comment by MattNot** [comment]
Mhh, github is strange. I'm not able to fork this repo for some reason.
This error appears:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/29925647/194748410-7ed1fd58-f176-4251-8d2e-c08902c86b5d.png">

Even if I erase the decription when forking

**Comment by zer0Kerbal** [comment]
> Mhh, github is strange. I'm not able to fork this repo for some reason. This error appears: 
> 
> Even if I erase the decription when forking
> 
> Edit: Nvm solved writing something else in the description.
> 
> Starting to work on this

it is a long description - used a script to put it there - it really needs to get trimmed.
